name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v4

# 1. Checkout the code
# 2. Instal docker buildx  docker/setup-buildx-action@v3
# 3. Build the docker image
# 4. Scan with trivy the built image

